### ISSUE TITLE
DoesNotExist at /accounts/github/login/ SocialApp matching query does not exist when trying to connect account to github

### ISSUE THREAD

**Issue by kwisatz** [sqawasmi/readthedocs-docker#1]
I'm unable to connect to a github account:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/accounts/github/login/?process=connect&next=%2Fdashboard%2Fimport%2F

Django Version: 1.6.6
Python Version: 2.7.3
Installed Applications:
['django.contrib.auth',
 'django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'pagination',
 'profiles',
 'taggit',
 'south',
 'djangosecure',
 'guardian',
 'django_gravatar',
 'rest_framework',
 'corsheaders',
 'djcelery',
 'haystack',
 'tastypie',
 'bookmarks',
 'builds',
 'core',
 'doc_builder',
 'oauth',
 'projects',
 'redirects',
 'rtd_tests',
 'restapi',
 'privacy',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'django_extensions']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'djangosecure.middleware.SecurityMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'core.middleware.SubdomainMiddleware',
 'core.middleware.SingleVersionMiddleware',
 'corsheaders.middleware.CorsMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/providers/oauth2/views.py" in view
  51.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/providers/oauth2/views.py" in dispatch
  71.         app = provider.get_app(self.request)
File "/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/providers/base.py" in get_app
  28.         return SocialApp.objects.get_current(self.id)
File "/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/models.py" in get_current
  30.                         provider=provider)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in get
  151.         return self.get_queryset().get(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in get
  310.                 self.model._meta.object_name)

Exception Type: DoesNotExist at /accounts/github/login/
Exception Value: SocialApp matching query does not exist.
```

**Comment by carukc** [comment]
Hi,  I'm having the same problem.  What did you do to fix?

**Comment by kwisatz** [comment]
I'm sorry, I don't remember. Should have mentioned it while closing the issue.

**Comment by carukc** [comment]
ok.  Thanks for the feedback.  I suspect that things are not yet configured correctly.  I think that it has to do with guthub auth API.  Ive configured but am getting a The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application error when I try to connect so I suspect that the wrong URI is being presented. I just need to figure out how to configure readthedocs with my own URL...

**Comment by slaki011** [comment]
kurac

**Comment by andrecarlucci** [comment]
Hi @carukc, did you manage to get it working? Cheers!

**Comment by carukc** [comment]
Hello,  I think that it was a DNS thing... but I will be repeating this work next week and will let you know for sure.  I think that I needed to create a host entry that pointed allowed each to resolve the proper name of the other.

**Comment by apeltzer** [comment]
Any news on this @carukc ? Just ran into the same error and some feedback would be highly appreciated!

**Comment by carukc** [comment]
Hi,  No progress.  It was not a DNS thing.  I'm still trying to figure what's going on but while working on this I've also discovered that source updates are taking quite some time to appear in the GUI.  So I suspect that the scheduled tasks are being delayed for some reason.  I'll post more information as I get it.

Thanks
Chris

**Comment by carukc** [comment]
Apologies... I have updated this issue with commentary from another... we are also having trouble getting GitLab to work properly and I was expecting feedback on that issue.

In this case the problem was that our system was not configured to be seen using the same URL if accessed from the inside and outside.  For github integration to work, everyone must be accessing the system internally and externally using the same URL.

I hope that this helps.
Chris

**Comment by tweep** [comment]
I added some comments to this ticket which addresses a similar issue: 

https://github.com/rtfd/readthedocs.org/issues/2243
